general {
  hide_cursor = true
}

background {
  monitor =
  path = screenshot
	blur_passes = 2
}

label {
  halign = center
  valign = top

  text = cmd[update:1000] date +"%H:%M"
  font_size = 60
  position = 0, -50
  color = rgb(81a2be)

  shadow_passes = 2
  shadow_size = 5
  shadow_color = rgba(0, 0, 0, 0.8)
}

label {
  halign = center
  valign = top

  text = cmd[update:60000] bash -c "date +'%A %d %B' && echo && cal -3"
  font_size = 18
  font_family = JetBrainsMono Nerd Font
  position = 0, -150
  color = rgb(81a2be)

  shadow_passes = 2
  shadow_size = 5
  shadow_color = rgba(0, 0, 0, 0.8)
}

input-field {
  size = 250, 50
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.3
  position = 0, 0
  font_color = rgb(81a2be)
  outer_color = rgb(81a2be)
  inner_color = rgba(20, 20, 20, 1.0)
}
