shell /run/current-system/sw/bin/zsh


# BEGIN_KITTY_THEME
# Atelier Lakeside Dark
include current-theme.conf
# END_KITTY_THEME

font_family Jetbrains Mono Nerd Font
bold_font Jetbrains Mono Nerd Font Bold
italic_font Jetbrains Mono Nerd Font Italic
bold_italic_font Jetbrains Mono Nerd Font Bold Italic

font_size 12

background_opacity 0.90
